url: "https://numerik-ea.github.io"
baseurl: "/bookmarklets-pour-le-rgaa-4.1.2/"

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .DS_Store
  - switch_gemfile.sh
  - LICENSE
