title: bookmarklets-rgaa-4.1.2
description: Scripts pour évaluer les critères du RGAA
theme: "minima"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .DS_Store
